# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'
target 'ProDonor' do
    # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  	use_frameworks!
  	pod 'GoogleMaps'
  	# Pods for ProDonor
	pod 'Google/CloudMessaging'
    pod 'Alamofire', '~> 3.1.2'
    pod 'KeychainSwift', git: 'https://github.com/marketplacer/keychain-swift.git', tag: '3.0.16'
    pod ‘Fabric’
    pod ‘Digits’
end
